"use client";

import { PageHeader } from "@/components/admin/page-header";
import { useDashboardMetrics } from "@/hooks/useAdmin";
import { formatRs } from "@/lib/format";

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-border bg-card p-5">
      <span className="text-sm text-muted-foreground">{label}</span>
      <p className="mt-2 text-2xl font-bold text-foreground">{value}</p>
    </div>
  );
}

export default function AdminReportsPage() {
  const { data, isLoading } = useDashboardMetrics();

  return (
    <>
      <PageHeader title="Reports &amp; Analytics" />
      <div className="space-y-6 p-8">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <StatCard
            label="Total Bookings"
            value={isLoading ? "—" : String(data?.bookings_all_time ?? 0)}
          />
          <StatCard label="Total Revenue" value={isLoading ? "—" : formatRs(data?.total_revenue ?? 0)} />
          <StatCard
            label="Active Users"
            value={isLoading ? "—" : String((data?.total_players ?? 0) + (data?.total_owners ?? 0))}
          />
          <StatCard label="Total Arenas" value={isLoading ? "—" : String(data?.total_arenas ?? 0)} />
        </div>

        <div className="rounded-xl border border-border bg-card p-6">
          <h3 className="font-semibold text-foreground">Downloadable reports</h3>
          <p className="mt-2 text-sm text-muted-foreground">
            PDF/CSV report downloads (user, arena, booking, revenue, system reports per
            docs/08_ADMIN_MODULE.md §9) are generated by the report module, which lands with
            notifications backend work. This page will grow export buttons here once that
            endpoint set exists — the metrics above are already live from{" "}
            <code className="rounded bg-muted px-1 py-0.5 text-xs">GET /admin/dashboard</code>.
          </p>
        </div>
      </div>
    </>
  );
}
