"""add matches

Adds matches + match_participants — the "Play" matchmaking feature. A match
is a deliberately lightweight social listing (arena/court/date/time/sport/
max-players); it does not reserve the court, so there's no FK to
time_slots and no payment fields.

Revision ID: dbb94d640aa3
Revises: b3691b51db41
Create Date: 2026-07-15 02:49:46.221161
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbb94d640aa3"
down_revision: str | None = "b3691b51db41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("arena_id", sa.UUID(), nullable=False),
        sa.Column("court_id", sa.UUID(), nullable=False),
        sa.Column("sport", sa.String(length=50), nullable=False),
        sa.Column("match_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "full", "cancelled", "completed", name="match_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["arena_id"], ["arenas.id"], name=op.f("fk_matches_arena_id_arenas"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["court_id"], ["courts.id"], name=op.f("fk_matches_court_id_courts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_matches_creator_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_index(op.f("ix_matches_arena_id"), "matches", ["arena_id"], unique=False)
    op.create_index(op.f("ix_matches_creator_id"), "matches", ["creator_id"], unique=False)
    op.create_index(op.f("ix_matches_status"), "matches", ["status"], unique=False)
    op.create_table(
        "match_participants",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_participants_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["users.id"],
            name=op.f("fk_match_participants_player_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_participants")),
        sa.UniqueConstraint(
            "match_id", "player_id", name="uq_match_participants_match_id_player_id"
        ),
    )
    op.create_index(
        op.f("ix_match_participants_match_id"), "match_participants", ["match_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_participants_player_id"), "match_participants", ["player_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_participants_player_id"), table_name="match_participants")
    op.drop_index(op.f("ix_match_participants_match_id"), table_name="match_participants")
    op.drop_table("match_participants")
    op.drop_index(op.f("ix_matches_status"), table_name="matches")
    op.drop_index(op.f("ix_matches_creator_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_arena_id"), table_name="matches")
    op.drop_table("matches")
    # drop_table doesn't drop the ENUM type it auto-created; without this a
    # re-upgrade fails on "type match_status already exists".
    sa.Enum(name="match_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
