"""add auth security columns and password history

Revision ID: f3dc8c5b1963
Revises: 0c8d2b789ebe
Create Date: 2026-07-13 07:50:17.093464
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3dc8c5b1963'
down_revision: str | None = '0c8d2b789ebe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_history'))
    )
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    # server_default backfills existing rows so the NOT NULL add succeeds.
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('users', sa.Column('pending_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # locked_until is an expiry timestamp compared against aware UTC now(); make
    # it timezone-aware to match otp/reset expiries and avoid naive/aware mixing.
    op.alter_column('users', 'locked_until', type_=sa.DateTime(timezone=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locked_until', type_=sa.DateTime())
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'pending_phone')
    op.drop_column('users', 'notification_preferences')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_table('password_history')
    # ### end Alembic commands ###
